### ISSUE TITLE
How to use modules

### ISSUE THREAD

**Issue by richardelima** [lnbits/lnbits-infinity#4]
What is the url of POS module?

**Comment by fiatjaf** [comment]
We still need to figure out a nice way to share these URLs, but meanwhile:

https://mod.fiatjaf.com/lnurlpos/lnurlpos.lua

**Comment by richardelima** [comment]
looks nice. but shows error at the end.
Alert Bad response from server. or Failed to decrypt payload: encryption scheme 20 not implemented (in blue wallet)
or Undefined 503 on lnbits legend.
or Unexpecxted token < in JSON at position 0. on Infinity lnbits

**Comment by fiatjaf** [comment]
This is the repository for issues specific to my modules: https://github.com/fiatjaf/lnbits-modules
