### ISSUE TITLE
Installation instruction fixes

### ISSUE THREAD

**Issue by dkeysil** [lnbits/lnbits-infinity#5]
System: Ubuntu 18.04.6 LTS

### Frontend:
1. Add that you have to install packages in client folder (just run `yarn` command)

2. If I'm just go with `yarn` and `quasar dev` commands I'm getting an error:
	1. `Error: Cannot find module 'vue/compiler-sfc'` - Fix for that error - [stackoverflow answer](https://stackoverflow.com/a/64548062)
	2. Then I'm getting `@vue/composition-api/dist/vue-composition-api.mjs not found` error - Fix for that `yarn add vue-demi`

I’m not well experienced with front, but I think here is something wrong with package.json file.

### Backend:
After `QUASAR_DEV_SERVER=http://localhost:8080 make dev` getting error:
`/usr/bin/ld: cannot find -llua5.3` - it' because `sudo apt-get install lua5.3` - not enough
`sudo apt install liblua5.3-dev` helped me

And add information that app will be able on port 5000 (not 8080 as someone can expect)

### Configs:
It would be great to have instructions on how to set the config parameters

**Comment by dkeysil** [comment]
@fiatjaf cc

**Comment by fiatjaf** [comment]
Thank you very much.

These JavaScript frameworks change so much, it's so annoying.
I've updated a bunch of things and now the frontend instructions should be working fine.
